apiVersion: v1
data:
  flink-conf.yaml: |
    akka.ask.timeout: 600s
    akka.lookup.timeout: 300s
    blob.fetch.num-concurrent: 100
    blob.server.port: 6124
    classloader.parent-first-patterns.default: java.;scala.;org.apache.flink.;org.apache.hadoop.;javax.annotation.;org.xml;javax.xml;org.apache.xerces;org.w3c;org.slf4j;org.apache.log4j;org.apache.logging;org.apache.commons.logging;ch.qos.logback
    cluster.evenly-spread-out-slots: true
    cluster.uncaught-exception-handling: FAIL
    env.java.opts: -Djava.io.tmpdir=/flink-tmp -Dlog4j2.formatMsgNoLookups=true
    env.java.opts.client: -Xms8G -Xmx8G
    env.java.opts.jobmanager: -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+PrintGC -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    env.java.opts.taskmanager: -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+PrintGC -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    execution.checkpointing.snapshot-compression: true
    execution.runtime-mode: BATCH
    heartbeat.timeout: 3600000
    io.tmp.dirs: /flink-tmp
    jobmanager.memory.enable-jvm-direct-memory-limit: true
    jobmanager.memory.jvm-metaspace.size: 1g
    jobmanager.memory.off-heap.size: 1g
    jobmanager.memory.process.size: 62260m
    jobmanager.retrieve-taskmanager-hostname: false
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.rpc.port: 6123
    jobstore.expiration-time: 36000
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.scope.variables.excludes: subtask_index;host;task_attempt_num;task_attempt_id;task_id
    pipeline.object-reuse: true
    query.server.port: 6125
    resourcemanager.taskmanager-timeout: 3600000
    rest.port: 8081
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 2147483647
    restart-strategy.fixed-delay.delay: 10s
    slot.request.timeout: 600000
    state.backend.local-recovery: true
    state.backend.rocksdb.localdir: /flink-tmp/rocksdb
    state.backend.rocksdb.metrics.actual-delayed-write-rate: true
    state.backend.rocksdb.metrics.background-errors: true
    state.backend.rocksdb.metrics.block-cache-capacity: true
    state.backend.rocksdb.metrics.block-cache-pinned-usage: true
    state.backend.rocksdb.metrics.block-cache-usage: true
    state.backend.rocksdb.metrics.column-family-as-variable: true
    state.backend.rocksdb.metrics.compactions-pending: true
    state.backend.rocksdb.metrics.cur-size-active-mem-table: true
    state.backend.rocksdb.metrics.cur-size-all-mem-tables: true
    state.backend.rocksdb.metrics.estimate-live-data-size: true
    state.backend.rocksdb.metrics.estimate-num-keys: true
    state.backend.rocksdb.metrics.estimate-pending-compaction-bytes: true
    state.backend.rocksdb.metrics.estimate-table-readers-mem: true
    state.backend.rocksdb.metrics.is-write-stopped: true
    state.backend.rocksdb.metrics.live-sst-files-size: true
    state.backend.rocksdb.metrics.mem-table-flush-pending: true
    state.backend.rocksdb.metrics.num-deletes-active-mem-table: true
    state.backend.rocksdb.metrics.num-deletes-imm-mem-tables: true
    state.backend.rocksdb.metrics.num-entries-active-mem-table: true
    state.backend.rocksdb.metrics.num-entries-imm-mem-tables: true
    state.backend.rocksdb.metrics.num-immutable-mem-table: true
    state.backend.rocksdb.metrics.num-live-versions: true
    state.backend.rocksdb.metrics.num-running-compactions: true
    state.backend.rocksdb.metrics.num-running-flushes: true
    state.backend.rocksdb.metrics.num-snapshots: true
    state.backend.rocksdb.metrics.size-all-mem-tables: true
    state.backend.rocksdb.predefined-options: FLASH_SSD_OPTIMIZED
    state.backend.rocksdb.use-bloom-filter: true
    table.exec.state.ttl: 10min
    taskmanager.memory.jvm-metaspace.size: 1g
    taskmanager.memory.managed.fraction: 0.5
    taskmanager.memory.network.fraction: 0.1
    taskmanager.memory.network.max: 35g
    taskmanager.memory.process.size: 31130m
    taskmanager.memory.task.off-heap.size: 2g
    taskmanager.network.blocking-shuffle.compression.enabled: true
    taskmanager.network.request-backoff.max: 600000
    taskmanager.numberOfTaskSlots: 7
    taskmanager.rpc.port: 6122
    taskmanager.runtime.large-record-handler: true
    taskmanager.slot.timeout: 600s
    web.cancel.enable: true
    web.submit.enable: true
    web.timeout: 600000
kind: ConfigMap
metadata:
  labels:
    app: flink
    cluster: flink
    flinkoperator.k8s.io/revision-name: flink-7c84bbff6d
  name: flink-configmap
  namespace: flink-dev
