apiVersion: apps/v1
kind: StatefulSet
# kind: Deployment
metadata:
  labels:
    app: flink
    cluster: flink
    component: jobmanager
    execution-id: flink
    flinkoperator.k8s.io/revision-name: flink-7c84bbff6d
    interruptible: "false"
  name: flink-jobmanager
  namespace: flink-dev
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flink
      cluster: flink
      component: jobmanager
      execution-id: flink
      interruptible: "false"
  serviceName: flink-jobmanager
  template:
    metadata:
      annotations:
        flyte.lyft.net/deployment: gke
        scheduling.k8s.io/group-name: flink-flink
      labels:
        app: flink
        cluster: flink
        component: jobmanager
        execution-id: flink
        interruptible: "false"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: trino-xpn-gew-dev-n1-hm-64
      containers:
        - args:
            - jobmanager
          image: flink:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "30"
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 60
            successThreshold: 1
            tcpSocket:
              port: 6123
            timeoutSeconds: 10
          name: jobmanager
          ports:
            - containerPort: 6123
              name: rpc
              protocol: TCP
            - containerPort: 6124
              name: blob
              protocol: TCP
            - containerPort: 6125
              name: query
              protocol: TCP
            - containerPort: 8081
              name: ui
              protocol: TCP
            - containerPort: 9249
              name: prom
              protocol: TCP
            - containerPort: 9999
              name: jmx
              protocol: TCP
          readinessProbe:
            failureThreshold: 60
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 6123
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "8"
              memory: 32Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /flink-tmp
              name: pvc-jm
            - mountPath: /opt/flink/conf
              name: flink-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 9999
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      volumes:
        - emptyDir: {}
          name: pvc-jm-default
        - configMap:
            defaultMode: 420
            name: flink-configmap
          name: flink-config-volume
        # - name: pvc-jm
        #   ephemeral:
        #     volumeClaimTemplate:
        #       spec:
        #         accessModes:
        #           - ReadWriteOnce
        #         resources:
        #           requests:
        #             storage: 128Gi
        #         storageClassName: pd-ssd
  # updateStrategy:
  #   rollingUpdate:
  #     partition: 0
  #   type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pvc-jm
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        storageClassName: pd-ssd
